### ISSUE TITLE
Case-insensitive operator

### ISSUE THREAD

**Issue by eldermorais** [68ociredef/spring-filter-ng#1]
In new version of spring-filter, the 'like' operator `~` is no longer case-insensitive. A new operator `~~` has been introduced for this purpose. I would like to request the consideration of including this new operator. Thank you in advance!

**Comment by 68ociredef** [comment]
Hi eldermorais, I have just published the 3.3.1 version in which the `like` operator  is now **case insensitive** (like in Spring Filter 2) while for case sensitive operator I have added `likeCs` operator.
Thank you for you suggest.
